name: Update Workflow

# This workflow is not really used, but it's a placeholder to trigger
# Renovate updates for this repository, this way we easier can update
# action.yml with new versions of the actions we depend on.

on:
  repository_dispatch:
    types: [update-workflow]

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set version to release tag 📝
        shell: bash
        run: npm version --allow-same-version --no-commit-hooks --no-git-tag-version from-git

      - name: Publish 🚀
        shell: bash
        run: yarn publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}

      - name: Push version changes to main branch 📤
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: release ${{ github.event.release.tag_name }}"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json
